-- 05/01/2021 23:10


CREATE TABLE `Despesa` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Empresa_Nome` VARCHAR(250) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Empresa_Segmento` VARCHAR(250) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Empresa_Logradouro` VARCHAR(250) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Empresa_Bairro` VARCHAR(250) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Empresa_Cidade` VARCHAR(250) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Empresa_Estado` VARCHAR(250) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Produto_Nome` VARCHAR(250) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Produto_Tipo` VARCHAR(250) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Produto_Marca` VARCHAR(250) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Produto_Descricao` VARCHAR(250) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Complemento` VARCHAR(250) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Forma_Pagamento` VARCHAR(250) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Quantidade` FLOAT NULL DEFAULT NULL,
	`Unidade` VARCHAR(250) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Valor_Unitario` FLOAT NULL DEFAULT NULL,
	`Valor_Total` FLOAT NULL DEFAULT NULL,
	`Data` DATE NULL DEFAULT NULL,
	`Hora` TIME NULL DEFAULT NULL,
	PRIMARY KEY (`Id`) USING BTREE
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1;


INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (9, 'Casa de Frango e Rotisseria Barao', 'Rotisseria', 'Avenida Albino J. B. de Oliveira, 1164', 'Barao Geraldo', 'Campinas', 'SP', 'Frango Assado', 'Alimentacao', '', '', NULL, 'Cartao Debito', 1, 'UN', 36, 36, '2021-01-02', '12:11:09');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (10, 'Casa de Frango e Rotisseria Barao', 'Rotisseria', 'Avenida Albino J. B. de Oliveira, 1164', 'Barao Geraldo', 'Campinas', 'SP', 'Farofa Pronta', 'Alimentacao', '', '', NULL, 'Cartao Debito', 0.5, 'KG', 20, 10, '2021-01-02', '12:11:09');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (11, 'Panificadora Nova Europa', 'Padaria', 'Avenida Santa Barbara do Rio Pardo, 690', 'Jardim Nova Europa', 'Campinas', 'SP', 'Biscoito de Polvilho', 'Alimentacao', 'Cassini', '100g', NULL, 'Cartao Alymente', 1, 'UN', 3.85, 3.85, '2021-01-02', '12:54:24');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (12, 'Panificadora Nova Europa', 'Padaria', 'Avenida Santa Barbara do Rio Pardo, 690', 'Jardim Nova Europa', 'Campinas', 'SP', 'Pao Frances', 'Alimentacao', '', '', NULL, 'Cartao Alymente', 0.378, 'KG', 13.99, 5.29, '2021-01-02', '12:54:24');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (13, 'Panificadora Nova Europa', 'Padaria', 'Avenida Santa Barbara do Rio Pardo, 690', 'Jardim Nova Europa', 'Campinas', 'SP', 'Salgadinho Cheetos', 'Alimentacao', 'Elma Chips', '37 g', NULL, 'Cartao Alymente', 1, 'UN', 2.3, 2.3, '2021-01-02', '12:54:24');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (14, 'Panificadora Nova Europa', 'Padaria', 'Avenida Santa Barbara do Rio Pardo, 690', 'Jardim Nova Europa', 'Campinas', 'SP', 'Salgadinho Cebolitos', 'Alimentacao', 'Elma Chips', '31 g', NULL, 'Cartao Alymente', 1, 'UN', 2.3, 2.3, '2021-01-02', '12:54:24');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (16, 'Panificadora Nova Europa', 'Padaria', 'Avenida Santa Barbara do Rio Pardo, 690', 'Jardim Nova Europa', 'Campinas', 'SP', 'Pao Frances', 'Alimentacao', '', '', NULL, 'Cartao Debito', 0.224, 'KG', 13.97, 3.13, '2021-01-03', '10:35:04');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (17, 'Shake Shake', 'Sorveteria', 'Praca Americo Buffo, 3', 'Jardim Nova Europa', 'Campinas', 'SP', 'Sorvete', 'Alimentacao', 'Sergel', '250ml', 'Leitinho Trufado', 'Cartao Debito', 1, 'UN', 7, 7, '2021-01-03', '10:43:39');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (19, 'Panificadora Nova Europa', 'Padaria', 'Avenida Santa Barbara do Rio Pardo, 690', 'Jardim Nova Europa', 'Campinas', 'SP', 'Pao Frances', 'Alimentacao', '', '', NULL, 'Cartao Debito', 0.17, 'KG', 14, 2.38, '2021-01-04', '09:22:26');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (20, 'O Recanto da Costela', 'Restaurante', 'Avenida Baden Powell, 1206', 'Jardim Nova Europa', 'Campinas', 'SP', 'Marmitex', 'Alimentacao', '', '', 'Costela Com Mandioca', 'Cartao Debito', 1, 'UN', 24, 24, '2021-01-04', '12:54:12');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (21, 'Belo Fruto Hortifruti', 'Mercado', 'Avenida Baden Powell, 1188', 'Jardim Nova Europa', 'Campinas', 'SP', 'Cerveja', 'Bebida', 'Heineken', '330ml', NULL, 'Cartao Debito', 2, 'UN', 9.99, 19.98, '2021-01-04', '13:03:58');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (22, 'Belo Fruto Hortifruti', 'Mercado', 'Avenida Baden Powell, 1188', 'Jardim Nova Europa', 'Campinas', 'SP', 'Salgadinho Bacon', 'Alimentacao', 'Fabitos', '90g', NULL, 'Cartao Debito', 1, 'UN', 3.49, 3.49, '2021-01-04', '13:03:58');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (23, 'Belo Fruto Hortifruti', 'Mercado', 'Avenida Baden Powell, 1188', 'Jardim Nova Europa', 'Campinas', 'SP', 'Agua Sem Gas', 'Bebida', 'Bonafont', '1.5 L', NULL, 'Cartao Debito', 1, 'UN', 3.49, 3.49, '2021-01-04', '13:03:58');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (24, 'McDonalds', 'Restaurante', 'Avenida Brasil, 750', 'Jardim Brasil', 'Campinas', 'SP', 'Lanche', 'Alimentacao', 'Mc Donalds', 'Cheeseburger', NULL, 'Cartao Debito', 1, 'UN', 7, 7, '2021-01-04', '19:45:41');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (25, 'McDonalds', 'Restaurante', 'Avenida Brasil, 750', 'Jardim Brasil', 'Campinas', 'SP', 'Lanche', 'Alimentacao', 'Mc Donalds', 'Extra Chicken', NULL, 'Cartao Debito', 2, 'UN', 6.9, 13.8, '2021-01-04', '19:45:41');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (26, 'McDonalds', 'Restaurante', 'Avenida Brasil, 750', 'Jardim Brasil', 'Campinas', 'SP', 'Milk Shake', 'Bebida', 'Mc Donalds', 'Morango', NULL, 'Cartao Debito', 1, 'UN', 13, 13, '2021-01-04', '19:45:41');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (27, 'Costelaria Carro de Boi', 'Restaurante', 'Avenida Aquidaba, 662', 'Bosque', 'Campinas', 'SP', 'Marmitex', 'Alimentacao', '', '', 'Carne de Panela', 'Cartao Debito', 1, 'UN', 27.49, 27.49, '2021-01-05', '13:09:21');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (28, 'Padaria Santo Expedito', 'Padaria', 'Evaristo da Veiga, 138', 'Jardim Santa Genebra', 'Campinas', 'SP', 'Agua Sem Gas', 'Bebida', 'Clarissima', '510 ml', NULL, 'Cartao Alymente', 1, 'UN', 2.5, 2.5, '2021-01-05', '17:49:03');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (29, 'Shake Shake', 'Sorveteria', 'Praca Americo Buffo, 3', 'Jardim Nova Europa', 'Campinas', 'SP', 'Sorvete', 'Alimentacao', 'Sergel', '90 g', 'Picole de Ovo Maltine', 'Cartao Debito', 1, 'UN', 7, 7, '2021-01-05', '17:04:49');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (30, 'Auto Posto Sao Tomaz', 'Posto de Combustivel', 'Avenida Baden Powell, 718', 'Jardim Nova Europa', 'Campinas', 'SP', 'Etanol Comum', 'Combustivel', '', '', NULL, 'Cartao Debito', 9.807, 'L', 3.059, 30, '2021-01-05', '17:15:28');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (31, 'Panificadora Nova Europa', 'Padaria', 'Avenida Santa Barbara do Rio Pardo, 690', 'Jardim Nova Europa', 'Campinas', 'SP', 'Biscoito de Polvilho', 'Alimentacao', 'Cassini', '100g', NULL, 'Cartao Debito', 1, 'UN', 3.85, 3.85, '2021-01-05', '17:22:56');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (32, 'Panificadora Nova Europa', 'Padaria', 'Avenida Santa Barbara do Rio Pardo, 690', 'Jardim Nova Europa', 'Campinas', 'SP', 'Pao Frances', 'Alimentacao', 'Panificadora Nova Europa', '', NULL, 'Cartao Debito', 0.304, 'KG', 13.98, 4.25, '2021-01-05', '17:22:56');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (33, 'Panificadora Nova Europa', 'Padaria', 'Avenida Santa Barbara do Rio Pardo, 690', 'Jardim Nova Europa', 'Campinas', 'SP', 'Mortadela', 'Alimentacao', 'Perdigao', '', NULL, 'Cartao Debito', 0.098, 'KG', 28.27, 2.77, '2021-01-05', '17:22:56');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (34, 'Panificadora Nova Europa', 'Padaria', 'Avenida Santa Barbara do Rio Pardo, 690', 'Jardim Nova Europa', 'Campinas', 'SP', 'Agua Sem Gas', 'Bebida', 'Crystal', '5 L', NULL, 'Cartao Debito', 1, 'UN', 8.99, 8.99, '2021-01-05', '17:22:56');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (35, 'Guilherme', 'Head Shop', 'Rua Evaristo da Veiga', 'Jardim Santa Genebra', 'Campinas', 'SP', 'Planta', 'Planta', '', '', NULL, 'Dinheiro', 0.01, 'KG', 25, 500, '2021-01-05', '18:29:55');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (36, 'Panificadora Nova Europa', 'Padaria', 'Avenida Santa Barbara do Rio Pardo, 690', 'Jardim Nova Europa', 'Campinas', 'SP', 'Cerveja', 'Bebida', 'Heineken', '330ml', NULL, 'Cartao Alymente', 1, 'UN', 8.99, 8.99, '2021-01-05', '22:57:38');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (37, 'Panificadora Nova Europa', 'Padaria', 'Avenida Santa Barbara do Rio Pardo, 690', 'Jardim Nova Europa', 'Campinas', 'SP', 'Pizza', 'Alimentacao', 'Panificadora Nova Europa', '', NULL, 'Cartao Alymente', 0.58, 'KG', 37.5, 21.75, '2021-01-05', '22:57:38');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (38, 'Panificadora Nova Europa', 'Padaria', 'Avenida Santa Barbara do Rio Pardo, 690', 'Jardim Nova Europa', 'Campinas', 'SP', 'Papel Higienico', 'Material de Limpeza', 'Neve', '4 Rolos', NULL, 'Cartao Alymente', 1, 'UN', 7.9, 7.9, '2021-01-05', '22:57:38');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (39, 'Panificadora Nova Europa', 'Padaria', 'Avenida Santa Barbara do Rio Pardo, 690', 'Jardim Nova Europa', 'Campinas', 'SP', 'Refrigerante', 'Bebida', 'Fanta Uva', '350 ml', NULL, 'Cartao Alymente', 1, 'UN', 3.7, 3.7, '2021-01-05', '22:57:38');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (40, 'Panificadora Nova Europa', 'Padaria', 'Avenida Santa Barbara do Rio Pardo, 690', 'Jardim Nova Europa', 'Campinas', 'SP', 'Limpador Multiuso', 'Material de Limpeza', 'Veja', '500 ml', NULL, 'Cartao Alymente', 1, 'UN', 4.9, 4.9, '2021-01-05', '22:57:38');
INSERT INTO `Despesa` (`Id`, `Empresa_Nome`, `Empresa_Segmento`, `Empresa_Logradouro`, `Empresa_Bairro`, `Empresa_Cidade`, `Empresa_Estado`, `Produto_Nome`, `Produto_Tipo`, `Produto_Marca`, `Produto_Descricao`, `Complemento`, `Forma_Pagamento`, `Quantidade`, `Unidade`, `Valor_Unitario`, `Valor_Total`, `Data`, `Hora`) VALUES (41, 'Panificadora Nova Europa', 'Padaria', 'Avenida Santa Barbara do Rio Pardo, 690', 'Jardim Nova Europa', 'Campinas', 'SP', 'Detergente Liquido', 'Material de Limpeza', 'Ype', '500 ml', NULL, 'Cartao Alymente', 1, 'UN', 2.25, 2.25, '2021-01-05', '22:57:38');